CREATE DATABASE IF NOT EXISTS MANGA_APP;
USE MANGA_APP;

CREATE TABLE IF NOT EXISTS COVER(
    COVER_ID INT PRIMARY KEY,
    COVER VARCHAR(250) NOT NULL
);
CREATE TABLE IF NOT EXISTS MANGA(
    MANGA_ID INT(10) UNIQUE NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    COVER_ID INT(10) FOREIGN KEY REFERENCES COVER(COVER_ID),
    UNIQUE(COVER_ID),
    PRIMARY KEY(MANGA_ID,COVER_ID)
);
CREATE TABLE IF NOT EXISTS CHAPTER(
    MANGA_ID INT(10) NOT NULL,
    MANGA_TITLE VARCHAR(40) NOT NULL,
    CHAPTER_ID INT(10) NOT NULL,
    CHAPTER_NUMBER INT(3) NOT NULL UNIQUE,
    CHAPTER_TITLE VARCHAR(40) NOT NULL UNIQUE,
    DATE_OF_UPLOADING DATE  NOT NULL,
    PRIMARY KEY(MANGA_ID,CHAPTER_ID),
    FOREIGN KEY(MANGA_ID) REFERENCES MANGA(MANGA_ID),
    FOREIGN KEY(MANGA_TITLE) REFERENCES MANGA(MANGA_TITLE)
);
CREATE TABLE IF NOT EXISTS GENRE(
    GENRE_ID INT(10) NOT NULL,
    "NAME" VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,

);
