DROP database IF EXISTS MANGA_APP;

CREATE DATABASE IF NOT EXISTS MANGA_APP;
--COMMENT
USE MANGA_APP;--COMMENT

CREATE TABLE IF NOT EXISTS COVER(
    COVER_ID INT(5) AUTO_INCREMENT PRIMARY KEY ,--COMMENT
    COVER_PATH VARCHAR(250) NOT NULL,
    WIDTH INT(5) NOT NULL,
    HEIGHT INT(5) NOT NULL
);
CREATE TABLE IF NOT EXISTS MANGA(
    MANGA_ID INT(10) NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    COVER_ID INT(10),
    UNIQUE (COVER_ID),
    UNIQUE (TITLE),
    CONSTRAINT PRIMARY KEY(MANGA_ID,COVER_ID),
    CONSTRAINT FOREIGN KEY (COVER_ID) REFERENCES COVER(COVER_ID),
    INDEX(COVER_ID)
);

CREATE TABLE IF NOT EXISTS CHAPTER(
    MANGA_ID INT(10) NOT NULL,
    MANGA_TITLE VARCHAR(40) NOT NULL,
    CHAPTER_ID INT(10) NOT NULL AUTO_INCREMENT,
    CHAPTER_NUMBER INT(3) NOT NULL,
    CHAPTER_TITLE VARCHAR(40) NOT NULL,
    DATE_OF_UPLOADING DATE NOT NULL,
    UNIQUE (CHAPTER_NUMBER),
    UNIQUE (CHAPTER_TITLE),
    CONSTRAINT PRIMARY KEY(MANGA_ID,CHAPTER_ID),
    CONSTRAINT FOREIGN KEY (MANGA_ID) REFERENCES MANGA(MANGA_ID),
    CONSTRAINT FOREIGN KEY (MANGA_TITLE) REFERENCES MANGA(TITLE),
    INDEX(MANGA_ID),
    INDEX(MANGA_TITLE),
    INDEX(CHAPTER_ID)
    );
CREATE TABLE IF NOT EXISTS GENRE(
    GENRE_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS MANGA_GENRE_RELATIONSHIP(
    MANGA_ID INT(10),
    GENRE_ID INT(10),
    CONSTRAINT FOREIGN KEY (MANGA_ID) REFERENCES MANGA(MANGA_ID),
    CONSTRAINT FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID),
    CONSTRAINT PRIMARY KEY (MANGA_ID,GENRE_ID),
    INDEX(MANGA_ID),
    INDEX(GENRE_ID)
);
