DROP DATABASE IF EXISTS MANGA_APP;
CREATE DATABASE MANGA_APP;
USE MANGA_APP;
CREATE TABLE COVER{
    COVER_ID INT NOT NULL PRIMARY KEY,
    COVER VARCHAR(250) NOT NULL;
};
CREATE TABLE MANGA{
    MANGA_ID INT(10) FOREIGN KEY REFERENCES COVER(),
    TITLE VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    COVER_ID INT(10) NOT NULL PRIMARY KEY;

};
ADD CONSTRAINT
CREATE TABLE
