/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.MangaApp.app;

import cat.uvic.teknos.m06.MangaApp.list.LinkedList;

import static cat.uvic.teknos.m06.MangaApp.utilities.StringUtils.join;
import static cat.uvic.teknos.m06.MangaApp.utilities.StringUtils.split;
import static cat.uvic.teknos.m06.MangaApp.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;
import java.sql.SQLException;
import java.sql.DriverManager;

public class App {
    public static void main(String[] args)  throws SQLException {
//         LinkedList tokens;
//         tokens = split(getMessage());
//         String result = join(tokens);
//         System.out.println(WordUtils.capitalize(result));
        try(var connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/test_1", "root", null);){
            connection.setAutoCommit(false); //automaticamente esta true
            var statement=connection.createStatement();
            var preparedStatement=connection.prepareStatement("select * from test_1.patat where asadsads=?");
            //statement.executeUpdate("insert into test_1.patat values (9,9,9,9);");
            //statement.executeUpdate("select * from test_1.patat");
//            var resultSet=statement.executeQuery("select * from test_1.patat");
            preparedStatement.setInt(1,Integer.parseInt(args[0]));
            var resultSet=preparedStatement.executeQuery();
            while(resultSet.next()){
                System.out.println("asadsads: "+resultSet.getInt("asadsads")+" asasasasas: "+resultSet.getInt("asasasasas"));
            }
            connection.commit();
        }
    }
}