/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.MangaApp.app;
import cat.uvic.teknos.m06.MangaApp.domain.modules.Cover;
import cat.uvic.teknos.m06.MangaApp.utilities.SchemaLoader;

import java.sql.SQLException;
import java.sql.DriverManager;

public class App {
    public static void main(String[] args)  throws SQLException {
    }
}