DROP database IF EXISTS pol;

CREATE DATABASE IF NOT EXISTS pol;

USE pol;

CREATE TABLE IF NOT EXISTS COVER(
    COVER_ID INT(3) PRIMARY KEY,
    COVER VARCHAR(250) NOT NULL,
    WIDTH INT(5) NOT NULL,
    HEIGHT INT(5) NOT NULL
);
CREATE TABLE IF EXISTS NOT MANGA( --there is a syntaxical sql error here, it should be 'IF NOT EXISTS'
    MANGA_ID INT(10) NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    COVER_ID INT(10),
    UNIQUE (COVER_ID),
    UNIQUE (TITLE),
    CONSTRAINT PRIMARY KEY(MANGA_ID,COVER_ID),
    CONSTRAINT FOREIGN KEY (COVER_ID) REFERENCES COVER(COVER_ID),
    INDEX(COVER_ID)
);
